### ISSUE TITLE
application crash when steam folder is selected

### ISSUE THREAD

**Issue by guigur** [paul-roman/vitrine#70]
When I select my steam folder, the app crash?
And if I re-launch it, it crash again

```
Error: ENOENT: no such file or directory, open 'S:\STEAM\steamapps\config\loginusers.vdf'
    at Object.fs.openSync (fs.js:646:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:538:29)
    at new e (C:\Users\guigur\AppData\Local\Programs\Vitrine\resources\app.asar\public\webpack:\sources\server\api\AcfParser.ts:15:15)
    at e.setSteamConfig (C:\Users\guigur\AppData\Local\Programs\Vitrine\resources\app.asar\public\webpack:\sources\server\api\SteamUserFinder.ts:14:25)
    at C:\Users\guigur\AppData\Local\Programs\Vitrine\resources\app.asar\public\webpack:\sources\server\api\SteamUserFinder.ts:44:19
    at new Promise (<anonymous>)
    at Object.t.findSteamUser (C:\Users\guigur\AppData\Local\Programs\Vitrine\resources\app.asar\public\webpack:\sources\server\api\SteamUserFinder.ts:43:9)
    at e.<anonymous> (C:\Users\guigur\AppData\Local\Programs\Vitrine\resources\app.asar\public\webpack:\sources\server\Server.ts:104:35)
    at C:\Users\guigur\AppData\Local\Programs\Vitrine\resources\app.asar\public\webpack:\node_modules\bluebird\js\release\promise.js:773:1
    at Object.next (C:\Users\guigur\AppData\Local\Programs\Vitrine\resources\app.asar\public\webpack:\node_modules\bluebird\js\release\promise.js:773:1)
    at C:\Users\guigur\AppData\Local\Programs\Vitrine\resources\app.asar\public\webpack:\node_modules\bluebird\js\release\promise.js:773:1
    at new Promise (<anonymous>)
    at r (C:\Users\guigur\AppData\Local\Programs\Vitrine\resources\app.asar\public\webpack:\node_modules\bluebird\js\release\promise.js:773:1)
    at e.clientSettingsAsked (C:\Users\guigur\AppData\Local\Programs\Vitrine\resources\app.asar\public\webpack:\sources\server\Server.ts:95:2)
```

**Comment by paul-roman** [comment]
I believe you chose your `steamapps` folder instead of the global Steam folder.
That misunderstanding shouldn't be happening, I'll put an indication.
Also, it would be interesting to prevent a global crash for this kind of things.

**Comment by guigur** [comment]
okay, i had to delete the appdata folder of vitrine.
And I retried the setup and same thing

note: I have a dedicated hdd for my games in S:\STEAM
```
Error: ENOENT: no such file or directory, open 'S:\STEAM\config\loginusers.vdf'
    at Object.fs.openSync (fs.js:646:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:538:29)
    at new e (C:\Users\guigur\AppData\Local\Programs\Vitrine\resources\app.asar\public\webpack:\sources\server\api\AcfParser.ts:15:15)
    at e.setSteamConfig (C:\Users\guigur\AppData\Local\Programs\Vitrine\resources\app.asar\public\webpack:\sources\server\api\SteamUserFinder.ts:14:25)
    at C:\Users\guigur\AppData\Local\Programs\Vitrine\resources\app.asar\public\webpack:\sources\server\api\SteamUserFinder.ts:44:19
    at new Promise (<anonymous>)
    at Object.t.findSteamUser (C:\Users\guigur\AppData\Local\Programs\Vitrine\resources\app.asar\public\webpack:\sources\server\api\SteamUserFinder.ts:43:9)
    at e.<anonymous> (C:\Users\guigur\AppData\Local\Programs\Vitrine\resources\app.asar\public\webpack:\sources\server\Server.ts:234:34)
    at C:\Users\guigur\AppData\Local\Programs\Vitrine\resources\app.asar\public\webpack:\node_modules\bluebird\js\release\promise.js:773:1
    at Object.next (C:\Users\guigur\AppData\Local\Programs\Vitrine\resources\app.asar\public\webpack:\node_modules\bluebird\js\release\promise.js:773:1)
    at s (C:\Users\guigur\AppData\Local\Programs\Vitrine\resources\app.asar\public\webpack:\node_modules\bluebird\js\release\promise.js:773:1)
    at <anonymous>
```

![image](https://user-images.githubusercontent.com/1360703/45933004-cdda6e00-bf85-11e8-85ae-5e1e06b32511.png)

**Comment by paul-roman** [comment]
Having `steamapps` somewhere else than the original Steam folder is not handled yet, this bug comes from the fact that the file needed is in `Disk:\[...]\Steam`\config\loginusers.vdf`. However, `steamapps` games will be searched starting from here, I believe there is another file to parse in order to get the path to every game source
