### ISSUE TITLE
impossible de lancer vitrine après la dernière mise a jour

### ISSUE THREAD

**Issue by guigur** [paul-roman/vitrine#82]
Vitrine s'est mis a jour vers 0.9.3
le soft a redémarrer mais ne s'est pas utilisable. il tourne en background et même en le kill la fenêtre n’apparaît pas.
j'ai supprimer appdata vitrine mais ça ne change rien

Les logs sont vides `Vitrine log
[ 03/10 07:41:27 ] Starting logging.`

**Comment by guigur** [comment]
j'ai redémarrer le Pc mais aucun changement

**Comment by paul-roman** [comment]
Je regarde ce soir

**Comment by guigur** [comment]
j'ai désinstaller vitrine et réinstaller et pareil

**Comment by guigur** [comment]
même résultat sur une VM windows 10

**Comment by paul-roman** [comment]
Même en supprimant `appdata\Roaming\Vitrine` et `appdata\Local\Programs\Vitrine` ?

**Comment by guigur** [comment]
Yep. J'ai fait une VM Windows 10 absolument neuve et pareil. Vitrine tourne en back, Les lits sont vides

**Comment by paul-roman** [comment]
Quel est l'output lorsque tu lances le soft depuis un terminal ?

**Comment by guigur** [comment]
`[PROCESS] Unhandled Promise Rejection
=====================================
{ Error: ENOTDIR, not a directory
    at notDirError (ELECTRON_ASAR.js:121:19)
    at Object.fs.mkdir (ELECTRON_ASAR.js:691:18)
    at Object.mkdir (C:\Users\guigur\AppData\Local\Programs\Vitrine\resources\app.asar\public\webpack:\node_modules\fs-extra\lib\mkdirs\mkdirs.js:34:1)
    at Promise (C:\Users\guigur\AppData\Local\Programs\Vitrine\resources\app.asar\public\webpack:\node_modules\universalify\index.js:19:1)
    at new Promise (<anonymous>)
    at Object.length (C:\Users\guigur\AppData\Local\Programs\Vitrine\resources\app.asar\public\webpack:\node_modules\universalify\index.js:12:1)
    at ensureDir (C:\Users\guigur\AppData\Local\Programs\Vitrine\resources\app.asar\public\webpack:\sources\server\Bootstrapper.ts:32:7)
    at fs$read (C:\Users\guigur\AppData\Local\Programs\Vitrine\resources\app.asar\public\webpack:\node_modules\graceful-fs\polyfills.js:119:1)
    at Object.fs$read [as next] (C:\Users\guigur\AppData\Local\Programs\Vitrine\resources\app.asar\public\webpack:\node_modules\graceful-fs\polyfills.js:119:1)
    at fs$read (C:\Users\guigur\AppData\Local\Programs\Vitrine\resources\app.asar\public\webpack:\node_modules\graceful-fs\polyfills.js:119:1) code: 'ENOTDIR', errno: -20 }
=====================================


`

**Comment by paul-roman** [comment]
C'est fix, ça venait du helper `isProduction()` qui ne fonctionnait plus et ne créait pas les dossiers en conséquence. Je publie un hotfix et je package ça

**Comment by guigur** [comment]
Niiice, je test la nouvelle version tout a l'heure
